### PR TITLE
Setup checkout cache for code review testing hook

### PR DESCRIPTION
**Pull request by La0**
Refs https://github.com/mozilla/code-review/issues/2193
Needed for https://github.com/mozilla/code-review/pull/2235

The goal here is to use Taskcluster cache on the firefox-ci [code-review testing hook](https://firefox-ci-tc.services.mozilla.com/hooks/project-relman/code-review-testing) so that mercurial checkouts can be shared amongst tasks.

I'm not sure if I need to declare that scope in `grants.yml` for the hook or if it's assigned automatically.

### CODE REVIEW

**Comment by bhearsum** [comment]
> I'm not sure if I need to declare that scope in `grants.yml` for the hook or if it's assigned automatically.

As far as I know, this will not happen automatically, and [the role](https://firefox-ci-tc.services.mozilla.com/auth/roles/hook-id%3Aproject-relman%2Fcode-review-testing) certainly doesn't have it already.

**Review by bhearsum — CHANGES_REQUESTED** [review]
Requesting changes for the grants.yml part.

**Comment by La0** [comment]
I added the scope request in `hooks.yml` relevant part

**Comment by La0** [comment]
Thank you, I added it there too

**Review by bhearsum — APPROVED** [review]

**Comment by La0** [comment]
Thanks for the merge & apply @bhearsum 

Unfortunately, Taskcluster still complains about missing scopes on [that task](https://firefox-ci-tc.services.mozilla.com/tasks/H54Y9g22RlmSiXERiCazQw/runs/0/logs/public/logs/live.log)

```
[taskcluster:error] Docker configuration could not be created.  This may indicate an authentication error when validating scopes necessary for running the task. 
 Error: Insufficient scopes to attach cache volumes.
The task is missing the following scopes:

[object Object]

This requested devices requires the task scopes to satisfy the following scope expression:
[object Object]
```

**Comment by jcristau** [comment]
Seems you're using generic-worker scopes in a docker-worker task, that won't work.

**Comment by La0** [comment]
> Seems you're using generic-worker scopes in a docker-worker task, that won't work.

Thanks for the quick reply ! I though that worker had moved towards generic-worker already.

I'l make another PR to simply request docker-worker cache

**Pull request merged**
