### PR TITLE
ci: install ci-admin in Decision tasks

### PR DESCRIPTION
**Pull request by ahal**
This fixes an issue when running the integration-test optimization.

### CODE REVIEW

**Review by bhearsum — APPROVED** [review]
Thanks!

**Comment by ahal** [comment]
Oops, this should have been draft, think I'm getting close though.

**Comment by ahal** [comment]
`uv` to the rescue!

**Comment by ahal** [comment]
Note that the integration tests are being scheduled on this PR because the optimization keeps them if anything under `/taskcluster` is modified. We can tweak this in a follow-up if we want to get more granular.

**Pull request merged**
